window.Streamly = window.Streamly || {};

(function () {

const categories = [
  'Усе',
  'React',
  'JavaScript',
  'TypeScript',
  'CSS',
  'Next.js',
  'Node.js',
  'Git',
  'UI/UX',
  'Backend',
  'Frontend',
  'DevOps',
  'Тренди',
  'Дизайн',
  'Освіта',
  'Подкасти',
  'Ігри',
  'Летсплеї',
  'Хорори',
  'Трейлери',
  'Інді',
  'Музика',
  'Live',
  'Новини',
  'Продуктивність',
  'Кібербезпека',
  'Data',
  'Mobile',
];

const baseVideos = [
  {
    id: 1,
    youtubeId: 'Tn6-PIqc4UM',
    title: 'React in 100 Seconds',
    channel: 'Fireship',
    avatar: 'FS',
    views: '1,3 млн',
    age: 'YouTube',
    category: 'React',
    duration: '2:22',
    verified: true,
    accent: '#e11d48',
    description: 'Коротке реальне YouTube-відео про React. Відкривається і програється прямо всередині Streamly.',
  },
  {
    id: 2,
    youtubeId: 'SqcY0GlETPk',
    title: 'React Tutorial for Beginners',
    channel: 'Programming with Mosh',
    avatar: 'PM',
    views: '4+ млн',
    age: 'YouTube',
    category: 'React',
    duration: '1:19:00',
    verified: true,
    accent: '#0f766e',
    description: 'Повний YouTube-урок React для початківців. Добре показує, що плеєр підтримує довгі відео.',
  },
  {
    id: 3,
    youtubeId: 'DHjqpvDnNGE',
    title: 'JavaScript in 100 Seconds',
    channel: 'Fireship',
    avatar: 'FS',
    views: '2+ млн',
    age: 'YouTube',
    category: 'JavaScript',
    duration: '2:24',
    verified: true,
    accent: '#eab308',
    description: 'Швидке реальне відео про JavaScript, яке можна знайти через пошук по назві або категорії.',
  },
  {
    id: 4,
    youtubeId: 'OEV8gMkCHXQ',
    title: 'CSS in 100 Seconds',
    channel: 'Fireship',
    avatar: 'FS',
    views: '1+ млн',
    age: 'YouTube',
    category: 'CSS',
    duration: '2:13',
    verified: true,
    accent: '#2563eb',
    description: 'Реальний ролик з YouTube про CSS. Картка, рекомендація і iframe використовують один `youtubeId`.',
  },
  {
    id: 5,
    youtubeId: 'Sklc_fQBmcs',
    title: 'Next.js in 100 Seconds',
    channel: 'Fireship',
    avatar: 'FS',
    views: '1+ млн',
    age: 'YouTube',
    category: 'Next.js',
    duration: '2:07',
    verified: true,
    accent: '#171717',
    description: 'Next.js відео для розділу з фреймворками і роботи з різними категоріями.',
  },
  {
    id: 6,
    youtubeId: 'hwP7WQkmECE',
    title: 'Git in 100 Seconds',
    channel: 'Fireship',
    avatar: 'FS',
    views: '1+ млн',
    age: 'YouTube',
    category: 'Git',
    duration: '2:00',
    verified: true,
    accent: '#ea580c',
    description: 'Коротке Git-відео з YouTube. Підходить для розділу рекомендацій і технічних добірок.',
  },
  {
    id: 7,
    youtubeId: '5qap5aO4i9A',
    title: 'lofi hip hop radio - beats to relax/study to',
    channel: 'Lofi Girl',
    avatar: 'LG',
    views: 'Live',
    age: 'YouTube',
    category: 'Музика',
    duration: 'LIVE',
    verified: true,
    accent: '#7c3aed',
    description: 'Реальний YouTube live/radio embed для музичної категорії.',
  },
  {
    id: 8,
    youtubeId: '8aGhZQkoFbQ',
    title: 'What the heck is the event loop anyway?',
    channel: 'JSConf',
    avatar: 'JS',
    views: '2+ млн',
    age: 'YouTube',
    category: 'Live',
    duration: '26:52',
    verified: true,
    accent: '#16a34a',
    description: 'Класична доповідь з YouTube про event loop. Добре працює як довший реальний контент.',
  },
  {
    id: 9,
    youtubeId: 'MmB9b5njVbA',
    title: 'Official Minecraft Trailer',
    channel: 'Minecraft',
    avatar: 'MC',
    views: '180+ млн',
    age: 'YouTube',
    category: 'Ігри',
    duration: '1:01',
    verified: true,
    accent: '#16a34a',
    description: 'Офіційний трейлер Minecraft для ігрової категорії.',
  },
  {
    id: 10,
    youtubeId: 'QkkoHAzjnUs',
    title: 'Grand Theft Auto V Trailer',
    channel: 'Rockstar Games',
    avatar: 'RG',
    views: '100+ млн',
    age: 'YouTube',
    category: 'Ігри',
    duration: '1:25',
    verified: true,
    accent: '#f97316',
    description: 'Офіційний трейлер GTA V з YouTube.',
  },
  {
    id: 11,
    youtubeId: 'zw47_q9wbBE',
    title: 'The Legend of Zelda: Breath of the Wild Trailer',
    channel: 'Nintendo',
    avatar: 'NT',
    views: '20+ млн',
    age: 'YouTube',
    category: 'Трейлери',
    duration: '3:50',
    verified: true,
    accent: '#0ea5e9',
    description: 'Кінематографічний трейлер Zelda для розділу трейлерів.',
  },
  {
    id: 12,
    youtubeId: 'E3Huy2cdih0',
    title: 'Elden Ring Gameplay Reveal',
    channel: 'Bandai Namco',
    avatar: 'BN',
    views: '15+ млн',
    age: 'YouTube',
    category: 'Ігри',
    duration: '3:03',
    verified: true,
    accent: '#a16207',
    description: 'Геймплейний трейлер Elden Ring для ігрових рекомендацій.',
  },
  {
    id: 13,
    youtubeId: 'iOztnsBPrAA',
    title: 'Five Nights at Freddy\'s - Part 1',
    channel: 'Markiplier',
    avatar: 'MK',
    views: '100+ млн',
    age: 'YouTube',
    category: 'Летсплеї',
    duration: '17:35',
    verified: true,
    accent: '#dc2626',
    description: 'Відомий летсплей FNAF з YouTube для добірки проходжень.',
  },
  {
    id: 14,
    youtubeId: 'uKA-IA4locM',
    title: 'Outlast Official Trailer',
    channel: 'Red Barrels',
    avatar: 'RB',
    views: '10+ млн',
    age: 'YouTube',
    category: 'Хорори',
    duration: '1:35',
    verified: true,
    accent: '#7f1d1d',
    description: 'Хорор трейлер Outlast для окремої темної категорії.',
  },
  {
    id: 15,
    youtubeId: 'xtxJtQa6VSw',
    title: 'Resident Evil 2 - E3 Announcement Trailer',
    channel: 'PlayStation',
    avatar: 'PS',
    views: '8+ млн',
    age: 'YouTube',
    category: 'Хорори',
    duration: '2:35',
    verified: true,
    accent: '#991b1b',
    description: 'Resident Evil 2 додає більше survival horror відео.',
  },
  {
    id: 16,
    youtubeId: '_UuktemkCFI',
    title: 'DOOM Eternal Official Launch Trailer',
    channel: 'Bethesda',
    avatar: 'BE',
    views: '12+ млн',
    age: 'YouTube',
    category: 'Ігри',
    duration: '2:23',
    verified: true,
    accent: '#b91c1c',
    description: 'Швидкий екшен трейлер DOOM Eternal.',
  },
  {
    id: 17,
    youtubeId: '91t0ha9x0AE',
    title: 'Hades - Official Animated Trailer',
    channel: 'Supergiant Games',
    avatar: 'SG',
    views: '5+ млн',
    age: 'YouTube',
    category: 'Інді',
    duration: '1:45',
    verified: true,
    accent: '#db2777',
    description: 'Інді трейлер Hades для різноманіття каталогу.',
  },
  {
    id: 18,
    youtubeId: 'UAO2urG23S4',
    title: 'Hollow Knight Release Trailer',
    channel: 'Team Cherry',
    avatar: 'TC',
    views: '7+ млн',
    age: 'YouTube',
    category: 'Інді',
    duration: '1:42',
    verified: true,
    accent: '#475569',
    description: 'Hollow Knight у категорії інді ігор.',
  },
  {
    id: 19,
    youtubeId: 'ot7uXNQskhs',
    title: 'Stardew Valley Trailer',
    channel: 'ConcernedApe',
    avatar: 'CA',
    views: '5+ млн',
    age: 'YouTube',
    category: 'Інді',
    duration: '1:24',
    verified: true,
    accent: '#22c55e',
    description: 'Затишний інді трейлер Stardew Valley.',
  },
  {
    id: 20,
    youtubeId: 'w7uOhFTrrq0',
    title: 'Terraria Official Trailer',
    channel: 'Re-Logic',
    avatar: 'RL',
    views: '3+ млн',
    age: 'YouTube',
    category: 'Інді',
    duration: '1:16',
    verified: true,
    accent: '#2563eb',
    description: 'Terraria додає sandbox та survival у стрічку.',
  },
  {
    id: 21,
    youtubeId: 'NSJ4cESNQfE',
    title: 'Among Us Steam Release Trailer',
    channel: 'Innersloth',
    avatar: 'IS',
    views: '6+ млн',
    age: 'YouTube',
    category: 'Ігри',
    duration: '1:03',
    verified: true,
    accent: '#ef4444',
    description: 'Among Us у загальній категорії ігор.',
  },
  {
    id: 22,
    youtubeId: '8X2kIfS6fb8',
    title: 'Cyberpunk 2077 Official E3 2018 Trailer',
    channel: 'Cyberpunk 2077',
    avatar: 'CP',
    views: '30+ млн',
    age: 'YouTube',
    category: 'Трейлери',
    duration: '1:39',
    verified: true,
    accent: '#facc15',
    description: 'Яскравий трейлер Cyberpunk для стрічки трейлерів.',
  },
  {
    id: 23,
    youtubeId: 'qPNiIeKMHyg',
    title: 'The Last of Us Part II - Official Trailer',
    channel: 'PlayStation',
    avatar: 'PS',
    views: '18+ млн',
    age: 'YouTube',
    category: 'Трейлери',
    duration: '2:47',
    verified: true,
    accent: '#334155',
    description: 'Сюжетний трейлер The Last of Us Part II.',
  },
  {
    id: 24,
    youtubeId: 'JSRtYpNRoN0',
    title: 'The Elder Scrolls V: Skyrim Official Trailer',
    channel: 'Bethesda',
    avatar: 'BE',
    views: '25+ млн',
    age: 'YouTube',
    category: 'Трейлери',
    duration: '2:52',
    verified: true,
    accent: '#64748b',
    description: 'Класичний трейлер Skyrim для фентезі ігор.',
  },
  {
    id: 25,
    youtubeId: 'FqnKB22pOC0',
    title: 'Overwatch Cinematic Trailer',
    channel: 'PlayOverwatch',
    avatar: 'OW',
    views: '50+ млн',
    age: 'YouTube',
    category: 'Трейлери',
    duration: '6:00',
    verified: true,
    accent: '#f59e0b',
    description: 'Кінематографічний трейлер Overwatch.',
  },
  {
    id: 26,
    youtubeId: '2Vv-BfVoq4g',
    title: 'Ed Sheeran - Perfect',
    channel: 'Ed Sheeran',
    avatar: 'ES',
    views: '3+ млрд',
    age: 'YouTube',
    category: 'Музика',
    duration: '4:40',
    verified: true,
    accent: '#ec4899',
    description: 'Музичне відео для неігрового розділу каталогу.',
  },
  {
    id: 27,
    youtubeId: 'n4IPBiB7SF4',
    title: 'The Last Night - 4K Trailer',
    channel: 'Xbox',
    avatar: 'XB',
    views: '2+ млн',
    age: 'YouTube',
    category: 'Інді',
    duration: '1:45',
    verified: true,
    accent: '#14b8a6',
    description: 'Стильний інді трейлер для різної візуальної стрічки.',
  },
  {
    id: 28,
    youtubeId: 'EsIEXKAxU6g',
    title: 'Five Nights at Freddy\'s #2',
    channel: 'jacksepticeye',
    avatar: 'JS',
    views: '40+ млн',
    age: 'YouTube',
    category: 'Летсплеї',
    duration: '14:12',
    verified: true,
    accent: '#22c55e',
    description: 'Летсплей jacksepticeye з Five Nights at Freddy\'s.',
  },
  {
    id: 29,
    youtubeId: 'yncoNo7tr2s',
    title: 'We finally play Minecraft!',
    channel: 'PewDiePie',
    avatar: 'PD',
    views: '20+ млн',
    age: 'YouTube',
    category: 'Летсплеї',
    duration: '12:41',
    verified: true,
    accent: '#ef4444',
    description: 'Minecraft летсплей з YouTube для розділу проходжень.',
  },
  {
    id: 30,
    youtubeId: 'KQ-xb16CNUE',
    title: 'Gmod Horror Map',
    channel: 'jacksepticeye',
    avatar: 'JS',
    views: '8+ млн',
    age: 'YouTube',
    category: 'Летсплеї',
    duration: '18:08',
    verified: true,
    accent: '#16a34a',
    description: 'Gmod horror map летсплей для суміші ігор та хорору.',
  },
  {
    id: 31,
    youtubeId: 'jDD_uxuzuPg',
    title: 'Five Nights At Freddy\'s 3 - Night 1-3',
    channel: 'iHasCupquake',
    avatar: 'IC',
    views: '6+ млн',
    age: 'YouTube',
    category: 'Летсплеї',
    duration: '21:30',
    verified: true,
    accent: '#ec4899',
    description: 'Ще один FNAF летсплей від іншого каналу.',
  },
  {
    id: 32,
    youtubeId: 'mynvzYOjAio',
    title: 'FNAF: Security Breach #1',
    channel: 'Absolute Voltz',
    avatar: 'AV',
    views: '2+ млн',
    age: 'YouTube',
    category: 'Летсплеї',
    duration: '35:02',
    verified: true,
    accent: '#a855f7',
    description: 'Довший летсплей Security Breach для стрічки проходжень.',
  },
  {
    id: 33,
    youtubeId: 'UdGpkggklNI',
    title: 'Five Nights at Freddy\'s 2 Walkthrough Part 1',
    channel: 'NukemDukem',
    avatar: 'ND',
    views: '5+ млн',
    age: 'YouTube',
    category: 'Летсплеї',
    duration: '28:22',
    verified: true,
    accent: '#f97316',
    description: 'Walkthrough FNAF 2 для категорії летсплеїв.',
  },
  {
    id: 34,
    youtubeId: 'y9SvS1locbI',
    title: 'Those Nights at Fredbears',
    channel: 'Big Holla',
    avatar: 'BH',
    views: '1+ млн',
    age: 'YouTube',
    category: 'Летсплеї',
    duration: '16:40',
    verified: true,
    accent: '#0f766e',
    description: 'Хорор-летсплей у стилі FNAF для більш різної стрічки.',
  },
];

const catalogTopics = [
  'повний випуск',
  'кращі моменти',
  'свіжа добірка',
  'швидкий старт',
  'розбір',
  'великий випуск',
  'топ момент',
  'новий сезон',
  'популярне зараз',
  'рекомендовано',
  'підбірка тижня',
  'коротка версія',
  'повна версія',
  'новий погляд',
  'відео дня',
  'нічний ефір',
];

const topicGroups = {
  Ігри: ['геймплей', 'трейлер', 'огляд', 'епічний момент', 'відкритий світ', 'битва з босом'],
  Летсплеї: ['перша серія', 'повне проходження', 'страшний момент', 'реакція', 'кращі моменти', 'нічний запис'],
  Хорори: ['страшний трейлер', 'survival horror', 'темний епізод', 'жахливий момент', 'напруга', 'нічний перегляд'],
  Трейлери: ['офіційний трейлер', 'анонс', 'геймплейний трейлер', 'кінематографічний ролик', 'премʼєра'],
  Інді: ['інді трейлер', 'затишний геймплей', 'піксельний стиль', 'метроїдванія', 'sandbox виживання'],
  Музика: ['кліп', 'live', 'плейлист', 'радіо', 'акустична версія'],
  React: ['урок', 'практика', 'компоненти', 'стан', 'хуки'],
  JavaScript: ['пояснення', 'основи', 'подія', 'асинхронність', 'приклади'],
  CSS: ['стилі', 'layout', 'анімації', 'адаптивність', 'практика'],
  Git: ['команди', 'workflow', 'основи', 'гілки', 'практика'],
};

function buildVideoCatalog(seedVideos, size = 1500) {
  return Array.from({ length: size }, (_, index) => {
    const seed = seedVideos[index % seedVideos.length];
    const category = seed.category;
    const topicList = topicGroups[category] || catalogTopics;
    const topic = topicList[index % topicList.length];
    const variant = Math.floor(index / seedVideos.length) + 1;

    return {
      ...seed,
      id: index + 1,
      title: variant === 1 ? seed.title : `${seed.title} · ${topic} #${variant}`,
      channel: seed.channel,
      avatar: seed.avatar,
      views: `${((index * 37) % 980) + 20} тис.`,
      age: index % 9 === 0 ? 'сьогодні' : `${(index % 28) + 1} дн. тому`,
      category,
      verified: index % 4 !== 0,
      description: `${seed.description} Категорія: ${category}. Добірка Streamly: ${topic}.`,
    };
  });
}

const videos = buildVideoCatalog(baseVideos, 3000);


window.Streamly.services = {
  ...(window.Streamly.services || {}),
  categories,
  baseVideos,
  buildVideoCatalog,
  videos,
};

})();
